# Project: Projet1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o camera.o car.o collision.o vector.o functions.o objloader.o player.o skybox.o game.o level.o text.o C:/library/glad/lib/glad.o captureVideo.o boutton.o sound.o
LINKOBJ  = main.o camera.o car.o collision.o vector.o functions.o objloader.o player.o skybox.o game.o level.o text.o C:/library/glad/lib/glad.o captureVideo.o boutton.o sound.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/library/SDL2_image-2.5.3/x86_64-w64-mingw32/lib" -L"C:/library/SDL2-2.0.12/x86_64-w64-mingw32/lib" -L"C:/library/SDL2_mixer-2.5.3/x86_64-w64-mingw32/lib" -L"C:/library/SDL2_ttf-2.19.3/x86_64-w64-mingw32/lib" -lopengl32 -lglu32 -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/library/SDL2-2.0.12/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_image-2.5.3/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_mixer-2.5.3/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_ttf-2.19.3/x86_64-w64-mingw32/include/SDL2"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/library/SDL2-2.0.12/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_image-2.5.3/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_mixer-2.5.3/x86_64-w64-mingw32/include/SDL2" -I"C:/library/SDL2_ttf-2.19.3/x86_64-w64-mingw32/include/SDL2"
BIN      = Projet1.exe
CXXFLAGS = $(CXXINCS) -std=c++0x
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

camera.o: camera.cpp
	$(CPP) -c camera.cpp -o camera.o $(CXXFLAGS)

car.o: car.cpp
	$(CPP) -c car.cpp -o car.o $(CXXFLAGS)

collision.o: collision.cpp
	$(CPP) -c collision.cpp -o collision.o $(CXXFLAGS)

vector.o: vector.cpp
	$(CPP) -c vector.cpp -o vector.o $(CXXFLAGS)

functions.o: functions.cpp
	$(CPP) -c functions.cpp -o functions.o $(CXXFLAGS)

objloader.o: objloader.cpp
	$(CPP) -c objloader.cpp -o objloader.o $(CXXFLAGS)

player.o: player.cpp
	$(CPP) -c player.cpp -o player.o $(CXXFLAGS)

skybox.o: skybox.cpp
	$(CPP) -c skybox.cpp -o skybox.o $(CXXFLAGS)

game.o: game.cpp
	$(CPP) -c game.cpp -o game.o $(CXXFLAGS)

level.o: level.cpp
	$(CPP) -c level.cpp -o level.o $(CXXFLAGS)

text.o: text.cpp
	$(CPP) -c text.cpp -o text.o $(CXXFLAGS)

C:/library/glad/lib/glad.o: C:/library/glad/lib/glad.c
	$(CPP) -c C:/library/glad/lib/glad.c -o C:/library/glad/lib/glad.o $(CXXFLAGS)

captureVideo.o: captureVideo.cpp
	$(CPP) -c captureVideo.cpp -o captureVideo.o $(CXXFLAGS)

boutton.o: boutton.cpp
	$(CPP) -c boutton.cpp -o boutton.o $(CXXFLAGS)

sound.o: sound.cpp
	$(CPP) -c sound.cpp -o sound.o $(CXXFLAGS)
